import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Nav from "./ui/navbar";
import { inter } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} antialiased`}>
        <Providers>
          <div className="border-y border-x rounded flex justify-center gap-9 items-center mx-auto max-w-screen-md m-4 h-14 bg-black sticky top-0">
            <Nav />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
